### ISSUE TITLE
Serbear doesn't show correct ranking positions anymore

### ISSUE THREAD

**Issue by Yo-shad** [towfiqi/serpbear#165]
Hey, Since last week, I'm trying to scan many websites for keywords positions but Serpbear fails to show the correct ones, for all the positions I only get **>100** even after refreshing many times, only few keywords actually show a correct position but most of them show **>100** I've changed the scraper but still get the same problem, any idea?

**Comment by towfiqi** [comment]
This has been already fixed in v1.0.2. Please make sure you are using the latest version.

**Comment by vncnt-mb** [comment]
Hello !

I'm taking the liberty of replying to this issue because I think it's still relevant.

I'm on the latest version of serpbear (v1.0.2) but unfortunately, the position that the scrapper retrieves is still not correct. I have the impression that the position information hasn't been updated since I upgraded to version 1.

Here are a few screenshots (I've masked the information but it's readable)

<img width="1122" alt="Capture d’écran 2024-02-16 à 11 54 55" src="https://github.com/towfiqi/serpbear/assets/48125944/3151eec4-a930-4916-9085-2d449040fbdb">

(detail of first keyword in the table)
<img width="524" alt="Capture d’écran 2024-02-16 à 11 57 06" src="https://github.com/towfiqi/serpbear/assets/48125944/ea67306f-c3b7-409a-8ac0-5b633a5a61e4">

(by the way, is it normal that the table is not aligned? :/)

thank you in advance! :)

**Comment by towfiqi** [comment]
Vincent, please share one of your keywords and the site address so I can recreate the issue in my instance.
And no, the table shouldn't look like that. Are your keywords longer than 2-3 words?

**Comment by vncnt-mb** [comment]
> Vincent, please share one of your keywords and the site address so I can recreate the issue in my instance.

I just tested with a new instance of serpbear, it works fine, I think there is a conflict with the old data since the upgrade. I'll export the domains and keywords to this one and it'll be perfect :) 

> And no, the table shouldn't look like that. Are your keywords longer than 2-3 words?

Yes :/ and the words are long. I think the "ellipsis" worked only with number of words and no with number of characters.

**Comment by towfiqi** [comment]
I cannot reproduce the issue in my instance of SerpBear. Keywords added before v1 work fine for me. 
Is it possible to send me your SQLite database? If it is, kindly send it to `tislam100@gmail.com`.

**Comment by DriesBultynck** [comment]
hey, i've experienced the same problem. Reinstalled serpbear and added 2 new domains. Keep getting >100 positions although we are in the top 10

**Comment by towfiqi** [comment]
Please zip your database.sql file inside the data folder or if you are using docker download it from your serpbear volume and send it to my email address posted previously.

**Comment by Yo-shad** [comment]
@towfiqi 👍 Thanks, everything went back to normal, Solved :white_check_mark:
